pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello Build!!!"'
                sh '''
                    echo "Welcome to Jenkins..."
                    echo "This is the new line in jenkins file"
                    echo "This is the 3rd line of jenkins file"
                    ls -lah
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        
    }
    
}
